장고7일차/selfstudy/self/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('selfs/', include('selfs.urls'))
]

장고7일차/selfstudy/selfs/urls.py
from django.urls import path
from . import views

app_name = 'selfs'

# CRUD
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:pk>/',views.detail,name='detail'),
    path('create/', views.create, name= 'create'),
    path('aaa/', views.aaa, name= 'aaa'),
    path('update/<int:pk>/', views.update, name= 'update'),
    path('edit/<int:pk>/', views.edit, name= 'edit'),
    path('delete/',views.delete,name='delete'),
]

장고7일차/selfstudy/selfs/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

장고7일차/selfstudy/selfs/views.py
from django.shortcuts import render,redirect
from .models import Article
# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    return render(request,'selfs/index.html',context)

def create(request):
    return render(request,'selfs/create.html')

def aaa(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    image = request.POST.get('image')
    created_at = request.POST.get('created_at')
    updated_at = request.POST.get('updated_at')

    article = Article()

    article.title = title
    article.content = content
    article.image = image
    article.created_at = created_at
    article.updated_at =updated_at

    article.save()

    return redirect('selfs:detail',article.pk)

def detail(request,pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'selfs/detail.html',context)

    return render(request,context)
def update(request,pk):
    title = request.POST.get('title')
    content = request.POST.get('content')
    image = request.POST.get('image')
    updated_at = request.POST.get('updated_at')

    article = Article.objects.get(pk=pk)

    article.title = title
    article.content = content
    article.image = image
    article.updated_at =updated_at

    article.save()

    return redirect('selfs:detail',article.pk)

def edit(request,pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'selfs/edit.html',context)

def delete(request,pk):
    pass

장고7일차/selfstudy/selfs/templates/selfs/create.html
{% extends "base.html" %}

{% block content %}
  <h1>글 작성 페이지</h1>
  <form action="{% url "selfs:aaa" %}" method="POST">
    {% csrf_token %}
    <label for="title">제목 : </label>
    <input type="text" name="title" id="title">
    <p></p>
    <label for="content">내용 : </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <hr>
    <input type="submit" value="작성하기">





  </form>

{% endblock content %}

장고7일차/selfstudy/selfs/templates/selfs/detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{article.pk}}번 째 글</h1>
<div>
  제목 : {{article.title}}
</div>
<div>
  내용 : {{article.content}}
</div>
<div>
  작성일자 : {{article.created_at}}
</div>
<div>
  수정일자 : {{article.updated_at}}
</div>

<a href="{% url "selfs:edit" article.pk %}"><input type="submit" value="수정하기"></a>

{% endblock content %}

장고7일차/selfstudy/selfs/templates/selfs/edit.html
{% extends "base.html" %}

{% block content %}
  <h1>글 수정 페이지</h1>
  <form action="{% url "selfs:update" article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">제목 : </label>
    <input type="text" name="title" id="title">
    <p></p>
    <label for="content">내용 : </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <hr>
    <input type="submit" value="작성하기">





  </form>

{% endblock content %}

장고7일차/selfstudy/selfs/templates/selfs/index.html
{% extends "base.html" %}

{% block content %}
<h1>WELCOME to Main(INDEX) PAGE</h1>
<a href="{% url "selfs:create" %}">새 글 쓰기</a>
<div>
  {% for article in  articles %}
    {{article.title}}
    {{article.content}}
  
  
  {% endfor %}

</div>

{% endblock content %}